shellEmulator: true

packages:
  - ./
  - playground

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - rollup
  - sharp
  - unrs-resolver
  - vue-demi
